### ISSUE TITLE
gcc34 not found ?

### ISSUE THREAD

**Issue by ghost** [whatsbcn/shellforge4#1]
I have an error like this 

<code>
<pre>
Kernel is linux
Compile gcc34 -O3 -S -fPIC -Winline -finline-functions -ffreestanding -fomit-frame-pointer -march=i386 -fPIC -isystem '/usr/include/sflib/' -isystem '/usr/include/sflib//linux_i386' -include /usr/include/sflib//linux_i386/sflib.h -o /tmp/sfA7YDo8/shell2.c.S /tmp/sfA7YDo8/shell2.c 2>&1
##[ERROR]## compiler reported error 127 while compiling /tmp/sfA7YDo8/shell2.c
##[ERROR]## sh: 1: gcc34: not found
</pre>
</code>

I tried to fix it myself, where is the `gcc34`?

**Comment by whatsbcn** [comment]
You can see in shellforge/shellforge.conf that the current configured compiler is gcc 3.4 and the expected binary name in the $PATH is "gcc34". You can change this name to your gcc binary name but you must ensure that it can be found by your shell.

**Comment by ghost** [comment]
Thank you ! :+1:

**Comment by CaledoniaProject** [comment]
Can you update the `shellforge.conf` and change `gcc34` to `gcc` by default?

**Comment by whatsbcn** [comment]
I remember that gcc34 was required in order to make shellforge work properly, this is why I don't want to change it by default.
