### ISSUE TITLE
Where I should find sflib.h ?

### ISSUE THREAD

**Issue by ghost** [whatsbcn/shellforge4#2]
Hello sir :) 

`sflib.h` not found in directory `/usr/include/sflib` 

Following the error like this : 

`##[ERROR]## cc1: fatal error: /usr/include/sflib//linux_i386/sflib.h: No such file or directory`

**Comment by whatsbcn** [comment]
First you should install sflib by executing install.sh in ./sflib directory.

I'm going to update the documentation with that. :)
