### ISSUE TITLE
Trouble with install.sh in sflib

### ISSUE THREAD

**Issue by h76** [whatsbcn/shellforge4#3]
Hi :)

I really appreciate what you've done in extending the original shellforge project, and I would really like to use it. However, when I try to run install.sh, I get this error:
Lydias-MacBook-Pro:shellforge4 lydiahogan$ sh /Users/lydiahogan/git/shellforge4/sflib/install.sh
/Users/lydiahogan/git/shellforge4/sflib/install.sh: line 7: ./gensflib.py: No such file or directory

When I run the same command in the sflib directory, I get this error:
Traceback (most recent call last):
  File "./gensflib.py", line 220, in <module>
    gen_sflib(source,dest)
  File "./gensflib.py", line 88, in gen_sflib
    open(dest+"common/sftypes.h","w").write(open(source+"common/sftypes.h").read())
IOError: [Errno 2] No such file or directory: '/usr/include//sflib/common/sftypes.h'

Any suggestions on how to fix this?

Thanks!
-Lydia

**Comment by h76** [comment]
Nevermind, I fixed it. Had to do sudo sh ./install.sh

**Comment by whatsbcn** [comment]
Documentation updated with your input!
